services:
  app:
    image: 3olen-symfony-demo
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    ports:
    - "8000:80"
    volumes:
    - .:/app
    command: ["php", "-S", "0.0.0.0:80", "public/index.php"]
    networks:
    - demo_network

  database:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_database
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
    - "3306:3306"
    volumes:
    - db_data:/var/lib/mysql
    networks:
    - demo_network

volumes:
  db_data:

networks:
  demo_network:
    driver: bridge
